CREATE TABLE SpringBooks(
 BookID    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
 BookTitle VARCHAR(50) NOT NULL,
 BookAuthor VARCHAR(50) NOT NULL,
 CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 MODIFIED_BY VARCHAR(20) DEFAULT USER ,
 PRIMARY KEY (  BookID)
)

create trigger set_updated_at_books
  before update on SpringBooks
  for each row
begin
  :new.updated_at := current_timestamp();
end;

INSERT INTO SpringBooks(BookTitle, BookAuthor)
VALUES ('Learn Spring Boot','Rishabh');

SELECT * from SpringBooks;